name: Bicep NSG deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main
    paths:
    - nsg-bicep/**
    - .github/workflows/nsg-deployment-bicep.yml
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This permissions block is needed when using OpenID authentication
permissions:
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@main
      name: Checkout

    # Log into Azure using Open ID
    - uses: azure/login@v1
      name: Azure OpenID login
      with:
        # Using just the "creds" line works but we can't set the subscription
        # creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: ${{ secrets.AZURE_CLIENT_ID_SANDBOX_OWNER }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_SANDBOX }}

    # Deploy Bicep file 
    # Documentation on arm-deploy module: https://github.com/Azure/arm-deploy
    - uses: azure/arm-deploy@v1
      name: Deploy NSG with Bicep
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID_SANDBOX }}
        resourceGroupName: rg-nsg-bicep-demo-westeu-01
        region: westeurope
        template: ./nsg-bicep/nsg-1.bicep
        parameters:
          location=westeurope 
          nsgName=nsg6-demo
        failOnStdErr: false